### ISSUE TITLE
Allow to specify multiple *.deb files for "rosenv add"

### ISSUE THREAD

**Issue by manuelmuehlig-HRI-EU** [HRI-EU/rosenv#8]
Right now, `rosenv add` only works with one explicit name and .deb file. It would be convenient to be able to specify a folder or multiple .deb files to install all of them into the virtual environment. The name resolution could then come from either the .deb filename (e.g., everything until the first _) or from some meta information in the .deb file itself.

**Comment by f-eisele** [comment]
thanks!
